### ISSUE TITLE
build fails with trailing slash in NDK_PATH

### ISSUE THREAD

**Issue by kristianlm** [chicken-mobile/android-chicken#3]
I tried with config.mk containing:

```
NDK_PATH ?= /opt/google/android/ndk/
```

Which (after a long time), fails because the toolchain doesn't get built. It shows no error of this, but tries to continue and can't find the toolchain binaries.

Perhaps we should automatically remove the trailing slash or produce a better error-message?

**Comment by mercora** [comment]
I wonder why this is a problem. shouldnt "/opt/google/android/ndk///////fooo" be a valid path also ?

**Comment by kristianlm** [comment]
You know what, I think you're right. I think the problem was that it wouldn't rebuild the toolchain when ./toolchain/android-14/ was present but empty. Should be fixed in with commit:4840b22b7ab4b81344ce8a71c77208768e805fa9
